- type: entity
  id: BkmCCBaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml

- type: entity
  id: BkmCCBaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
#      balance: 75000
    - type: StationCargoOrderDatabase
      orders:
        Cargo: [ ]
        Engineering: [ ]
        Medical: [ ]
        Science: [ ]
        Security: [ ]
        Service: [ ]
    - type: StationCargoBountyDatabase
    - type: TradeStation
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: CargoDeliveryData
